//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdityaMinerals.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_L_BILLINGPART2
    {
        public long ID { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public string ProductionDescription_VC { get; set; }
        public string HSNCODE_VC { get; set; }
        public string UOM_VC { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> ValueofSupply { get; set; }
        public Nullable<int> Sno { get; set; }
    
        public virtual ADM_L_BILLINGPART1 ADM_L_BILLINGPART1 { get; set; }
    }
}
