//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdityaMinerals.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_M_BILLINGPRODUCTS
    {
        public int Sno { get; set; }
        public string ProductDescription { get; set; }
    }
}
