//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdityaMinerals.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdityamineralsEntities : DbContext
    {
        public AdityamineralsEntities()
            : base("name=AdityamineralsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADM_M_USER> ADM_M_USER { get; set; }
        public virtual DbSet<ADM_L_BILLINGPART1> ADM_L_BILLINGPART1 { get; set; }
        public virtual DbSet<ADM_L_BILLINGPART2> ADM_L_BILLINGPART2 { get; set; }
        public virtual DbSet<ADM_M_BILLINGPRODUCTS> ADM_M_BILLINGPRODUCTS { get; set; }
        public virtual DbSet<ADM_M_UOM> ADM_M_UOM { get; set; }
    }
}
