using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using AdityaMinerals.Models;
using Newtonsoft.Json;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using CsvHelper;
using System.Globalization;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.Drawing;

namespace AdityaMinerals.BussinessLayer
{
    public class ReportGenerationService
    {
        public byte[] GenerateReport(EnhancedReportModel reportModel, ReportFormat format)
        {
            switch (format)
            {
                case ReportFormat.PDF:
                    return GeneratePdfReport(reportModel);
                case ReportFormat.Excel:
                    return GenerateExcelReport(reportModel);
                case ReportFormat.CSV:
                    return GenerateCsvReport(reportModel);
                case ReportFormat.JSON:
                    return GenerateJsonReport(reportModel);
                default:
                    throw new ArgumentException("Unsupported report format");
            }
        }

        private byte[] GeneratePdfReport(EnhancedReportModel reportModel)
        {
            using (var memoryStream = new MemoryStream())
            {
                var document = new Document(PageSize.A4, 25, 25, 30, 30);
                var writer = PdfWriter.GetInstance(document, memoryStream);
                
                document.Open();

                // Add title
                var titleFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 18, BaseColor.BLACK);
                var title = new Paragraph(reportModel.ReportTitle, titleFont)
                {
                    Alignment = Element.ALIGN_CENTER,
                    SpacingAfter = 20
                };
                document.Add(title);

                // Add metadata
                var metadataFont = FontFactory.GetFont(FontFactory.HELVETICA, 10, BaseColor.GRAY);
                var metadata = new Paragraph($"Generated on: {reportModel.GeneratedDate:yyyy-MM-dd HH:mm:ss} by {reportModel.GeneratedBy}", metadataFont)
                {
                    Alignment = Element.ALIGN_RIGHT,
                    SpacingAfter = 20
                };
                document.Add(metadata);

                // Add content based on report type
                switch (reportModel.ReportType)
                {
                    case ReportType.Invoice:
                        AddInvoiceContentToPdf(document, (InvoiceReportData)reportModel.Data);
                        break;
                    case ReportType.SalesReport:
                        AddSalesContentToPdf(document, (SalesReportData)reportModel.Data);
                        break;
                    case ReportType.ProductSummary:
                        AddProductContentToPdf(document, (ProductReportData)reportModel.Data);
                        break;
                    case ReportType.CustomerReport:
                        AddCustomerContentToPdf(document, (CustomerReportData)reportModel.Data);
                        break;
                }

                document.Close();
                return memoryStream.ToArray();
            }
        }

        private byte[] GenerateExcelReport(EnhancedReportModel reportModel)
        {
            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add(reportModel.ReportTitle);

                // Add header
                worksheet.Cells[1, 1].Value = reportModel.ReportTitle;
                worksheet.Cells[1, 1].Style.Font.Size = 16;
                worksheet.Cells[1, 1].Style.Font.Bold = true;

                worksheet.Cells[2, 1].Value = $"Generated on: {reportModel.GeneratedDate:yyyy-MM-dd HH:mm:ss}";
                worksheet.Cells[3, 1].Value = $"Generated by: {reportModel.GeneratedBy}";

                int startRow = 5;

                // Add content based on report type
                switch (reportModel.ReportType)
                {
                    case ReportType.Invoice:
                        AddInvoiceContentToExcel(worksheet, (InvoiceReportData)reportModel.Data, startRow);
                        break;
                    case ReportType.SalesReport:
                        AddSalesContentToExcel(worksheet, (SalesReportData)reportModel.Data, startRow);
                        break;
                    case ReportType.ProductSummary:
                        AddProductContentToExcel(worksheet, (ProductReportData)reportModel.Data, startRow);
                        break;
                    case ReportType.CustomerReport:
                        AddCustomerContentToExcel(worksheet, (CustomerReportData)reportModel.Data, startRow);
                        break;
                }

                // Auto-fit columns
                worksheet.Cells.AutoFitColumns();

                return package.GetAsByteArray();
            }
        }

        private byte[] GenerateCsvReport(EnhancedReportModel reportModel)
        {
            using (var memoryStream = new MemoryStream())
            using (var writer = new StreamWriter(memoryStream))
            using (var csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
            {
                // Write header information
                csv.WriteField("Report Title");
                csv.WriteField(reportModel.ReportTitle);
                csv.NextRecord();

                csv.WriteField("Generated Date");
                csv.WriteField(reportModel.GeneratedDate.ToString("yyyy-MM-dd HH:mm:ss"));
                csv.NextRecord();

                csv.WriteField("Generated By");
                csv.WriteField(reportModel.GeneratedBy);
                csv.NextRecord();
                csv.NextRecord(); // Empty line

                // Add content based on report type
                switch (reportModel.ReportType)
                {
                    case ReportType.SalesReport:
                        AddSalesContentToCsv(csv, (SalesReportData)reportModel.Data);
                        break;
                    case ReportType.ProductSummary:
                        AddProductContentToCsv(csv, (ProductReportData)reportModel.Data);
                        break;
                    case ReportType.CustomerReport:
                        AddCustomerContentToCsv(csv, (CustomerReportData)reportModel.Data);
                        break;
                    default:
                        csv.WriteField("Data export not supported for this report type in CSV format");
                        csv.NextRecord();
                        break;
                }

                writer.Flush();
                return memoryStream.ToArray();
            }
        }

        private byte[] GenerateJsonReport(EnhancedReportModel reportModel)
        {
            var json = JsonConvert.SerializeObject(reportModel, Formatting.Indented);
            return Encoding.UTF8.GetBytes(json);
        }

        // PDF Content Methods
        private void AddInvoiceContentToPdf(Document document, InvoiceReportData data)
        {
            var headerFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 12);
            var normalFont = FontFactory.GetFont(FontFactory.HELVETICA, 10);

            // Invoice header info
            document.Add(new Paragraph($"Invoice No: {data.InvoiceHeader?.InvoiceNo}", headerFont));
            document.Add(new Paragraph($"Date: {data.InvoiceHeader?.DateOfIssue:yyyy-MM-dd}", normalFont));
            document.Add(new Paragraph($"Customer: {data.InvoiceHeader?.BP_Name_VC}", normalFont));
            document.Add(new Paragraph(" ")); // Space

            // Invoice items table
            var table = new PdfPTable(5);
            table.WidthPercentage = 100;

            // Headers
            table.AddCell(new PdfPCell(new Phrase("Product", headerFont)));
            table.AddCell(new PdfPCell(new Phrase("Quantity", headerFont)));
            table.AddCell(new PdfPCell(new Phrase("Rate", headerFont)));
            table.AddCell(new PdfPCell(new Phrase("Amount", headerFont)));
            table.AddCell(new PdfPCell(new Phrase("Net Amount", headerFont)));

            // Data rows
            foreach (var item in data.InvoiceItems ?? new List<AdityaMinerals.EntityModels.ADM_L_BILLINGPART2>())
            {
                table.AddCell(new PdfPCell(new Phrase(item.ProductionDescription_VC ?? "", normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.QTY?.ToString() ?? "0", normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.Rate?.ToString("C") ?? "0", normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.Amount?.ToString("C") ?? "0", normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.ValueofSupply?.ToString("C") ?? "0", normalFont)));
            }

            document.Add(table);

            // Totals
            document.Add(new Paragraph(" "));
            document.Add(new Paragraph($"Total Amount: {data.TotalAmount:C}", headerFont));
            document.Add(new Paragraph($"Total Discount: {data.TotalDiscount:C}", headerFont));
            document.Add(new Paragraph($"Net Amount: {data.NetAmount:C}", headerFont));
        }

        private void AddSalesContentToPdf(Document document, SalesReportData data)
        {
            var headerFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 12);
            var normalFont = FontFactory.GetFont(FontFactory.HELVETICA, 10);

            // Summary
            document.Add(new Paragraph($"Report Period: {data.ReportPeriodStart:yyyy-MM-dd} to {data.ReportPeriodEnd:yyyy-MM-dd}", headerFont));
            document.Add(new Paragraph($"Total Sales: {data.TotalSales:C}", headerFont));
            document.Add(new Paragraph($"Total Invoices: {data.TotalInvoices}", headerFont));
            document.Add(new Paragraph(" "));

            // Sales items table
            var table = new PdfPTable(5);
            table.WidthPercentage = 100;

            table.AddCell(new PdfPCell(new Phrase("Invoice No", headerFont)));
            table.AddCell(new PdfPCell(new Phrase("Date", headerFont)));
            table.AddCell(new PdfPCell(new Phrase("Customer", headerFont)));
            table.AddCell(new PdfPCell(new Phrase("Amount", headerFont)));
            table.AddCell(new PdfPCell(new Phrase("Net Amount", headerFont)));

            foreach (var item in data.SalesItems ?? new List<SalesSummaryItem>())
            {
                table.AddCell(new PdfPCell(new Phrase(item.InvoiceNo.ToString(), normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.InvoiceDate.ToString("yyyy-MM-dd"), normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.CustomerName ?? "", normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.InvoiceAmount.ToString("C"), normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.NetAmount.ToString("C"), normalFont)));
            }

            document.Add(table);
        }

        private void AddProductContentToPdf(Document document, ProductReportData data)
        {
            var headerFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 12);
            var normalFont = FontFactory.GetFont(FontFactory.HELVETICA, 10);

            document.Add(new Paragraph($"Total Products: {data.TotalProducts}", headerFont));
            document.Add(new Paragraph(" "));

            var table = new PdfPTable(4);
            table.WidthPercentage = 100;

            table.AddCell(new PdfPCell(new Phrase("Product Name", headerFont)));
            table.AddCell(new PdfPCell(new Phrase("HSN Code", headerFont)));
            table.AddCell(new PdfPCell(new Phrase("UOM", headerFont)));
            table.AddCell(new PdfPCell(new Phrase("Unit Price", headerFont)));

            foreach (var item in data.Products ?? new List<ProductSummaryItem>())
            {
                table.AddCell(new PdfPCell(new Phrase(item.ProductName ?? "", normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.HSNCode ?? "", normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.UOM ?? "", normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.UnitPrice.ToString("C"), normalFont)));
            }

            document.Add(table);
        }

        private void AddCustomerContentToPdf(Document document, CustomerReportData data)
        {
            var headerFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 12);
            var normalFont = FontFactory.GetFont(FontFactory.HELVETICA, 10);

            document.Add(new Paragraph($"Total Customers: {data.TotalCustomers}", headerFont));
            document.Add(new Paragraph($"Total Business Value: {data.TotalBusinessValue:C}", headerFont));
            document.Add(new Paragraph(" "));

            var table = new PdfPTable(5);
            table.WidthPercentage = 100;

            table.AddCell(new PdfPCell(new Phrase("Customer Name", headerFont)));
            table.AddCell(new PdfPCell(new Phrase("GSTIN", headerFont)));
            table.AddCell(new PdfPCell(new Phrase("State", headerFont)));
            table.AddCell(new PdfPCell(new Phrase("Total Orders", headerFont)));
            table.AddCell(new PdfPCell(new Phrase("Purchase Value", headerFont)));

            foreach (var item in data.Customers ?? new List<CustomerSummaryItem>())
            {
                table.AddCell(new PdfPCell(new Phrase(item.CustomerName ?? "", normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.GSTIN ?? "", normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.State ?? "", normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.TotalOrders.ToString(), normalFont)));
                table.AddCell(new PdfPCell(new Phrase(item.TotalPurchaseValue.ToString("C"), normalFont)));
            }

            document.Add(table);
        }

        // Excel Content Methods
        private void AddInvoiceContentToExcel(ExcelWorksheet worksheet, InvoiceReportData data, int startRow)
        {
            int row = startRow;

            // Invoice header
            worksheet.Cells[row, 1].Value = "Invoice No:";
            worksheet.Cells[row, 2].Value = data.InvoiceHeader?.InvoiceNo;
            row++;

            worksheet.Cells[row, 1].Value = "Date:";
            worksheet.Cells[row, 2].Value = data.InvoiceHeader?.DateOfIssue;
            row++;

            worksheet.Cells[row, 1].Value = "Customer:";
            worksheet.Cells[row, 2].Value = data.InvoiceHeader?.BP_Name_VC;
            row += 2;

            // Headers
            worksheet.Cells[row, 1].Value = "Product";
            worksheet.Cells[row, 2].Value = "Quantity";
            worksheet.Cells[row, 3].Value = "Rate";
            worksheet.Cells[row, 4].Value = "Amount";
            worksheet.Cells[row, 5].Value = "Net Amount";

            // Style headers
            using (var range = worksheet.Cells[row, 1, row, 5])
            {
                range.Style.Font.Bold = true;
                range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                range.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.LightGray);
            }

            row++;

            // Data
            foreach (var item in data.InvoiceItems ?? new List<AdityaMinerals.EntityModels.ADM_L_BILLINGPART2>())
            {
                worksheet.Cells[row, 1].Value = item.ProductionDescription_VC;
                worksheet.Cells[row, 2].Value = item.QTY;
                worksheet.Cells[row, 3].Value = item.Rate;
                worksheet.Cells[row, 4].Value = item.Amount;
                worksheet.Cells[row, 5].Value = item.ValueofSupply;
                row++;
            }

            // Totals
            row++;
            worksheet.Cells[row, 4].Value = "Total Amount:";
            worksheet.Cells[row, 5].Value = data.TotalAmount;
            worksheet.Cells[row, 4, row, 5].Style.Font.Bold = true;
        }

        private void AddSalesContentToExcel(ExcelWorksheet worksheet, SalesReportData data, int startRow)
        {
            int row = startRow;

            // Summary
            worksheet.Cells[row, 1].Value = "Total Sales:";
            worksheet.Cells[row, 2].Value = data.TotalSales;
            row++;

            worksheet.Cells[row, 1].Value = "Total Invoices:";
            worksheet.Cells[row, 2].Value = data.TotalInvoices;
            row += 2;

            // Headers
            worksheet.Cells[row, 1].Value = "Invoice No";
            worksheet.Cells[row, 2].Value = "Date";
            worksheet.Cells[row, 3].Value = "Customer";
            worksheet.Cells[row, 4].Value = "Amount";
            worksheet.Cells[row, 5].Value = "Net Amount";

            using (var range = worksheet.Cells[row, 1, row, 5])
            {
                range.Style.Font.Bold = true;
                range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                range.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.LightGray);
            }

            row++;

            foreach (var item in data.SalesItems ?? new List<SalesSummaryItem>())
            {
                worksheet.Cells[row, 1].Value = item.InvoiceNo;
                worksheet.Cells[row, 2].Value = item.InvoiceDate;
                worksheet.Cells[row, 3].Value = item.CustomerName;
                worksheet.Cells[row, 4].Value = item.InvoiceAmount;
                worksheet.Cells[row, 5].Value = item.NetAmount;
                row++;
            }
        }

        private void AddProductContentToExcel(ExcelWorksheet worksheet, ProductReportData data, int startRow)
        {
            int row = startRow;

            worksheet.Cells[row, 1].Value = "Total Products:";
            worksheet.Cells[row, 2].Value = data.TotalProducts;
            row += 2;

            // Headers
            worksheet.Cells[row, 1].Value = "Product Name";
            worksheet.Cells[row, 2].Value = "HSN Code";
            worksheet.Cells[row, 3].Value = "UOM";
            worksheet.Cells[row, 4].Value = "Unit Price";

            using (var range = worksheet.Cells[row, 1, row, 4])
            {
                range.Style.Font.Bold = true;
                range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                range.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.LightGray);
            }

            row++;

            foreach (var item in data.Products ?? new List<ProductSummaryItem>())
            {
                worksheet.Cells[row, 1].Value = item.ProductName;
                worksheet.Cells[row, 2].Value = item.HSNCode;
                worksheet.Cells[row, 3].Value = item.UOM;
                worksheet.Cells[row, 4].Value = item.UnitPrice;
                row++;
            }
        }

        private void AddCustomerContentToExcel(ExcelWorksheet worksheet, CustomerReportData data, int startRow)
        {
            int row = startRow;

            worksheet.Cells[row, 1].Value = "Total Customers:";
            worksheet.Cells[row, 2].Value = data.TotalCustomers;
            row++;

            worksheet.Cells[row, 1].Value = "Total Business Value:";
            worksheet.Cells[row, 2].Value = data.TotalBusinessValue;
            row += 2;

            // Headers
            worksheet.Cells[row, 1].Value = "Customer Name";
            worksheet.Cells[row, 2].Value = "GSTIN";
            worksheet.Cells[row, 3].Value = "State";
            worksheet.Cells[row, 4].Value = "Total Orders";
            worksheet.Cells[row, 5].Value = "Purchase Value";

            using (var range = worksheet.Cells[row, 1, row, 5])
            {
                range.Style.Font.Bold = true;
                range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                range.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.LightGray);
            }

            row++;

            foreach (var item in data.Customers ?? new List<CustomerSummaryItem>())
            {
                worksheet.Cells[row, 1].Value = item.CustomerName;
                worksheet.Cells[row, 2].Value = item.GSTIN;
                worksheet.Cells[row, 3].Value = item.State;
                worksheet.Cells[row, 4].Value = item.TotalOrders;
                worksheet.Cells[row, 5].Value = item.TotalPurchaseValue;
                row++;
            }
        }

        // CSV Content Methods
        private void AddSalesContentToCsv(CsvWriter csv, SalesReportData data)
        {
            // Headers
            csv.WriteField("Invoice No");
            csv.WriteField("Date");
            csv.WriteField("Customer");
            csv.WriteField("Amount");
            csv.WriteField("Net Amount");
            csv.NextRecord();

            // Data
            foreach (var item in data.SalesItems ?? new List<SalesSummaryItem>())
            {
                csv.WriteField(item.InvoiceNo);
                csv.WriteField(item.InvoiceDate.ToString("yyyy-MM-dd"));
                csv.WriteField(item.CustomerName);
                csv.WriteField(item.InvoiceAmount);
                csv.WriteField(item.NetAmount);
                csv.NextRecord();
            }
        }

        private void AddProductContentToCsv(CsvWriter csv, ProductReportData data)
        {
            csv.WriteField("Product Name");
            csv.WriteField("HSN Code");
            csv.WriteField("UOM");
            csv.WriteField("Unit Price");
            csv.NextRecord();

            foreach (var item in data.Products ?? new List<ProductSummaryItem>())
            {
                csv.WriteField(item.ProductName);
                csv.WriteField(item.HSNCode);
                csv.WriteField(item.UOM);
                csv.WriteField(item.UnitPrice);
                csv.NextRecord();
            }
        }

        private void AddCustomerContentToCsv(CsvWriter csv, CustomerReportData data)
        {
            csv.WriteField("Customer Name");
            csv.WriteField("GSTIN");
            csv.WriteField("State");
            csv.WriteField("Total Orders");
            csv.WriteField("Purchase Value");
            csv.NextRecord();

            foreach (var item in data.Customers ?? new List<CustomerSummaryItem>())
            {
                csv.WriteField(item.CustomerName);
                csv.WriteField(item.GSTIN);
                csv.WriteField(item.State);
                csv.WriteField(item.TotalOrders);
                csv.WriteField(item.TotalPurchaseValue);
                csv.NextRecord();
            }
        }

        public string GetContentType(ReportFormat format)
        {
            switch (format)
            {
                case ReportFormat.PDF:
                    return "application/pdf";
                case ReportFormat.Excel:
                    return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                case ReportFormat.CSV:
                    return "text/csv";
                case ReportFormat.JSON:
                    return "application/json";
                default:
                    return "application/octet-stream";
            }
        }

        public string GetFileExtension(ReportFormat format)
        {
            switch (format)
            {
                case ReportFormat.PDF:
                    return ".pdf";
                case ReportFormat.Excel:
                    return ".xlsx";
                case ReportFormat.CSV:
                    return ".csv";
                case ReportFormat.JSON:
                    return ".json";
                default:
                    return ".bin";
            }
        }
    }
}
